# Generated by Django 5.0.1 on 2024-01-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jps', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
