# Generated by Django 5.0.1 on 2024-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_comment_options_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата комментария'),
        ),
    ]
