# Generated by Django 5.0.1 on 2024-01-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата комментария'),
        ),
    ]
