# Generated by Django 5.0.1 on 2024-03-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_categories_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
